# STEP1: build a docker image using docker build . -t my-node-red
# STEP2: docker-compose up -d

version: "3"
services:
  broker:
    image: eclipse-mosquitto
    restart: always
    #volumes:
    #  - "./mosquitto/config:/mosquitto/config"
    #  - "./mosquitto/data:/mosquitto/data"
    #  - "./mosquitto/log:/mosquitto/log"
    ports:
      - "1883:1883"
    #user: "0"
    #user: ${CURRENT_UID} 
    networks:
      - localnet
  node-red:
    depends_on:
      - broker #use "broker" as the mqtt-addres in node-red
    image: my-node-red
    restart: always
    volumes:
      - "./node-red:/data"
    ports:
      - "1880:1880"
    user: "0"
    #user: ${CURRENT_UID} 
    networks: 
      - localnet
      
networks: 
  localnet: 
    driver: bridge    
